name: Release

on:
  release:
    types: [ "published" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Build Plugin Zip
        run: ./gradlew buildPlugin

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/distributions/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}